%macro roccalc(PC=);
ods html file ="C:\TheBook\EM14.1\Reports\Chapter5\RespRateV.html";
title "Validation Data Set";
proc freq data=&EM_LIB..MdlComp_Validate;
 table resp / nopercent nocum out=tab1(keep= resp count rename=(count=N));
run;
ods html close ;
ods html file ="C:\TheBook\EM14.1\Reports\Chapter5\RespRateV_cutoff.html";
Title "Cases with Predicted Probability (P_resp1) GE &PC";
title2 "Validation Data Set";
proc freq data=&EM_LIB..MdlComp_Validate;
  table resp / nopercent nocum out=tab2(keep= resp count rename=(count=NC));
  where P_resp1 ge &PC;
run;
ods html close;
data temp;
 merge tab1 tab2 ;
 by resp ;
 if resp=0 then TYPE='FPR' ; else if resp=1 then TYPE='TPR'; Rate= NC/N;
 cutoff=&pc;
 run;
ods html file ="C:\TheBook\EM14.1\Reports\Chapter5\TPR_FPR_Cutoff.html";
 Title "True Positive Rate (TPR) and False Positive Rate (FPR)";
 title2 "at cut-off = &PC";
proc print data=temp label noobs;
 var RESP N NC TYPE RATE ;
 label N = "Number of Observations in the sample";
 label NC = "Number of Observations classified as responders ";
 label RESP = "Actual RESPONSE ";
 label TYPE = "ROC Coordinate  ";
 label Rate = "ROC Coordinate Value";
 run;
ods html close;
%mend roccalc;
%roccalc(PC=0.02);
