proc means data=validate noprint ;
  class dec ;
  var delbal ;
  output out= outsum sum(delbal) = sum_delbal mean(delbal)=mean_delbal;
run ;
data Total(keep=sum_delbal rename=(sum_delbal=Tot_delbal)) deciles ;
  set outsum ;
  if _TYPE_ = 0 then output Total;
  else output deciles ;
run ;
data total ;
  set total ;
  scale = &scale/tot_delbal ;
run ;
data tables ;
 set deciles ;
 if _N_ = 1 then set total ;
run;
data lib2.Lift_&model ;
 set tables ;
 retain cumsum 0 nobs 0;
 sum_delbal= sum_delbal*scale ;
 tot_delbal= tot_delbal*scale ;
 mean_delbal = mean_delbal*scale;
 cumsum + sum_delbal ;
 capc = 100*cumsum/tot_delbal ;
 gmean = tot_delbal/&nv1 ;
 nobs+_freq_ ;
 meanc = cumsum/nobs ;
 liftc = meanc/gmean;
run ;
